version: "3.8"

services:
  # Frontend
  front:
    build: .
    container_name: shiraishi-labs
    tty: true
    volumes:
      - ./:/workspaces/shiraishi-labs:cached
    # ports:
    #   - 5173:5173
    networks:
      - poc-api-network

networks:
  poc-api-network:
    driver: bridge
